version: "3"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy:/etc/caddy"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: bash -c 'sleep 3 && npm start'

volumes:
  caddy_data:
  caddy_config:
