version: "3"
services:
  app:
    image: palms450/app-demo:latest
    build:
      dockerfile: Dockerfile.production
      context: .
    command:  bash -c 'sleep 3 && npm test'
    env_file:
      - app/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    env_file:
      - app/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
