name: ci
on: push

env:
  TEST_TAG: palms450/app-demo:test
  POD_TAG: palms450/app-demo:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile.production
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile.production
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.PROD_TAG }}
