name: ci
on: push

env:
  IMG_NAME: palms450/app-demo


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
  
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMG_NAME }}:test
          cache-to: type=inline
          push: true
          tags: ${{ env.IMG_NAME }}:test

      - name: Test
        run: |
          make compose-test

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMG_NAME }}:test
          push: true
          tags: ${{ env.IMG_NAME }}::latest
